# Generated by Django 4.1 on 2024-04-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_userurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userurls',
            old_name='Url model',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='userurls',
            old_name='User',
            new_name='user',
        ),
    ]
